// Package cst defines the data structure for the concrete syntax tree.
//
// These struct definitions are put in a standalone package because the code
// generated by gocc imports them. A standalone package helps avoid circular
// dependencies.
package cst

import (
	"fmt"

	"github.com/agodnic/avmc/parser/generated/token"
)

type TypeEnum int

const (
	TypeEnum_Void   TypeEnum = iota
	TypeEnum_Uint64 TypeEnum = iota
	TypeEnum_String TypeEnum = iota
)

type (
	IntLit struct {
		Value string
	}
	StrLit struct {
		Value string
	}
	BinOp struct {
		R  any
		Op string
		L  any
	}
	UnaryOp struct {
		Op   string
		Expr any
	}
	Ident struct {
		PackageName string
		Ident       string
	}
	Call struct {
		Ident any
		Args  any
	}
	Type struct {
		TypeEnum TypeEnum
	}
	VarDecl struct {
		Ident string
		Type  any
		Expr  any
	}
	ConstDecl struct {
		Ident string
		Type  any
		Expr  any
	}
	Assignment struct {
		Ident string
		Expr  any
	}
	Return struct {
		Expr any
	}
	Block struct {
		Stmts []any
	}
	If struct {
		Cond any
		Then Block
		Else any
	}
	FuncDecl struct {
		Ident  string
		Params []Param
		Type   Type
		Block  Block
	}
	Param struct {
		Ident string
		Type  any
	}
)

func AppendToParamSlice(slice, item any) ([]Param, error) {
	s := slice.([]Param)
	i := item.(Param)
	return append(s, i), nil
}

func MakeParam(ident, ty any) (Param, error) {
	result := Param{
		Ident: string(ident.(*token.Token).Lit),
		Type:  ty.(Type),
	}
	return result, nil
}

func MakeFuncDecl(tIdent, args, ty, block any) (FuncDecl, error) {

	result := FuncDecl{
		Ident:  string(tIdent.(*token.Token).Lit),
		Params: args.([]Param),
		Block:  block.(Block),
	}

	if ty == nil {
		// NOTE This will have no src line/span information (if we ever add the feature)
		result.Type.TypeEnum = TypeEnum_Void
	} else {
		result.Type = ty.(Type)
	}
	return result, nil
}

func MakeIf(t0, t1, t2 any) (If, error) {
	result := If{
		Cond: t0,
		Then: t1.(Block),
		Else: t2,
	}
	return result, nil
}

func MakeBlock(t0 any) (Block, error) {
	result := Block{
		Stmts: t0.([]any),
	}
	return result, nil
}

func MakeReturn(t0 any) (Return, error) {
	result := Return{
		Expr: t0,
	}
	return result, nil
}

func MakeAssignment(t0, t1 any) (Assignment, error) {
	result := Assignment{
		Ident: string(t0.(*token.Token).Lit),
		Expr:  t1,
	}
	return result, nil
}

func MakeConstDecl(t0, t1, t2 any) (ConstDecl, error) {
	result := ConstDecl{
		Ident: string(t0.(*token.Token).Lit),
		Type:  t1,
		Expr:  t2,
	}
	return result, nil
}

func MakeVarDecl(t0, t1, t2 any) (VarDecl, error) {
	result := VarDecl{
		Ident: string(t0.(*token.Token).Lit),
		Type:  t1,
		Expr:  t2,
	}
	return result, nil
}

func MakeType(t0 any) (Type, error) {

	str := string(t0.(*token.Token).Lit)

	var val TypeEnum
	switch str {
	case "uint64":
		val = TypeEnum_Uint64
	case "string":
		val = TypeEnum_String
	default:
		return Type{}, fmt.Errorf("unexpected type: %s", str)
	}

	result := Type{
		TypeEnum: val,
	}
	return result, nil
}

func MakeCall(t0, t1 any) (Call, error) {
	result := Call{
		Ident: t0,
		Args:  t1,
	}
	return result, nil
}

func MakeIdent(t0, t1 any) (Ident, error) {
	result := Ident{
		Ident: string(t1.(*token.Token).Lit),
	}
	if t0 != nil {
		result.PackageName = string(t0.(*token.Token).Lit)
	}
	return result, nil
}

func MakeUnaryOp(t0, t1 any) (UnaryOp, error) {
	result := UnaryOp{
		Op:   string(t0.(*token.Token).Lit),
		Expr: t1,
	}
	return result, nil
}

func MakeBinOp(t0, t1, t2 any) (BinOp, error) {
	result := BinOp{
		R:  t0,
		Op: string(t1.(*token.Token).Lit),
		L:  t2,
	}
	return result, nil
}

func MakeIntLit(t any) (IntLit, error) {
	result := IntLit{
		Value: string(t.(*token.Token).Lit),
	}
	return result, nil
}

func MakeStrLit(t any) (StrLit, error) {
	s := string(t.(*token.Token).Lit)
	result := StrLit{
		Value: s[1 : len(s)-1],
	}
	return result, nil
}
